### ISSUE TITLE
Permission to include this add-on in another

### ISSUE THREAD

**Issue by sobjornstad** [Kenishi/Answer-Key-Cascade#3]
I've done some hacking to produce a nice key layout for reviewing with a numeric keypad and I would like to publish it, but your code doesn't have a license listed, so I thought I should check with you in case you have a problem with my reusing it. The part my add-on uses is almost exactly what you have on the website with the exception that it modifies the ease so that all the numbers move "down one" (i.e., 0 is fail, 3 is easy).

I would of course give you credit in the add-on and on the description page.

**Comment by sobjornstad** [comment]
(I would like to publish this add-on under the GPL3+ since I've incorporated some other GPL code.)

**Comment by Kenishi** [comment]
You are more than welcome to use the code how you wish. I should update the
license to be lglp or apache.

**Comment by sobjornstad** [comment]
Cheers. Thanks for the add-on in the first place, by the way. :-)
